dkie:
  k1_16: 1
  k2_16: 1
  k3_16: 1
  kie1p: 1.03
  kie1s: 1
  kie2p: 1
  kie2s: 1
  kie3p: 1
  kie3s: 1
  penalty_k2: 1
  penalty_k4: 0.001
  dh2o: 20
  dcpo: 10
  conc_h2o: 55.5
  conc_cpo: 0.001

outfile: mk_scenario_1_2c.png

timerange:
  type: logspace
  start: -8
  stop: -2
  num: 100

